print ("Укажите координаты точки A")
x = int(input())
y = int(input())
print ("Укажите координаты точки B")
x1 = int(input())
y1 = int(input())
distance = pow(pow(x1-x,2)+pow(y1-y,2),0.5)
print (distance)